/** Electro City lamps & LED lighting — sourced from EC catalogue PDF + cross-refs. */

export type LampProduct = {
  /** Catalogue SKU / brand code */
  sku: string;
  /** Electro City internal stock number when listed */
  stockNo?: string;
  /** Secondary / alt code from the PDF line */
  altCode?: string;
  title: string;
  application: string;
  /** Filter category */
  category:
    | "Truck & trailer"
    | "Work & spot"
    | "Light bars"
    | "Side markers"
    | "Strobe & rotating"
    | "Number plate"
    | "Tail & indicator"
    | "Marker lamps"
    | "Interior"
    | "Special";
  voltage?: string;
  colour?: string;
  notes?: string;
  imageSrc?: string;
};

/**
 * Full line from Electro City “LAMPS AND LED LIGHTING” catalogue (Jul 2021 PDF).
 * Descriptions cleaned from catalogue abbreviations; volts/colours inferred from the line.
 */
export const LAMP_PRODUCTS: LampProduct[] = [
  {
    sku: "104232AM",
    stockNo: "431739",
    title: "LED truck light — amber",
    application: "12–24V 32-LED truck light, amber",
    category: "Truck & trailer",
    voltage: "12–24V",
    colour: "Amber",
  },
  {
    sku: "1160A",
    stockNo: "220247",
    title: "Round spot / fog lamp",
    application: "Round spot fog lamp with rubber grommet",
    category: "Work & spot",
    notes: "Supplied with rubber grommet",
  },
  {
    sku: "123 G",
    stockNo: "213248",
    title: "Square green lamp 120×120 mm",
    application: "120×120 mm square green signal / marker lamp",
    category: "Special",
    colour: "Green",
  },
  {
    sku: "133206BM",
    stockNo: "431740",
    title: "LED number plate lamp",
    application: "12–24V LED number plate lamp",
    category: "Number plate",
    voltage: "12–24V",
  },
  {
    sku: "2VA923149011",
    stockNo: "213295",
    altCode: "VA3149",
    title: "Ford stop / tail / indicator — LH",
    application: "Red/amber stop-tail-flasher lamp for Ford, left-hand",
    category: "Tail & indicator",
    colour: "Red / amber",
    notes: "Catalogue: RED/AMB.S/T/F.FORD LH",
  },
  {
    sku: "30000G",
    stockNo: "213299",
    title: "Large green strobe — 220V",
    application: "220V large green strobe lamp",
    category: "Strobe & rotating",
    voltage: "220V",
    colour: "Green",
  },
  {
    sku: "351 RH",
    stockNo: "213305",
    title: "Toyota Hilux tail lamp — RH",
    application: "Right-hand tail lamp for Toyota Hilux",
    category: "Tail & indicator",
  },
  {
    sku: "BL5A",
    stockNo: "213313",
    title: "Oblong surface-mount amber lamp",
    application: "Oblong surface-mount amber BL5 lamp",
    category: "Marker lamps",
    colour: "Amber",
  },
  {
    sku: "CLC847A",
    stockNo: "220249",
    title: "Rectangular spot lamp — amber",
    application: "Rectangular amber spot lamp",
    category: "Work & spot",
    colour: "Amber",
  },
  {
    sku: "DJ5001",
    stockNo: "213320",
    title: "5¾″ sealed beam — outer",
    application: "5¾″ semi sealed-beam outer lamp",
    category: "Work & spot",
    notes: "Catalogue: 53/4 SEMI S/SB OUT",
  },
  {
    sku: "DJ5002",
    stockNo: "213321",
    title: "5¾″ sealed beam — inner",
    application: "5¾″ semi sealed-beam inner lamp",
    category: "Work & spot",
    notes: "Catalogue: 53/4 SEMI S/SB IN",
  },
  {
    sku: "E15R",
    stockNo: "E15R",
    title: "Round stop lamp 76 mm — red beehive",
    application: "76 mm round red beehive stop lamp",
    category: "Tail & indicator",
    colour: "Red",
  },
  {
    sku: "E31",
    stockNo: "220346",
    title: "Number plate lamp — black Sterling",
    application: "Black Sterling number plate lamp",
    category: "Number plate",
  },
  {
    sku: "HY-088H LED31C",
    altCode: "TL5LED / 0103-00018",
    title: "LED truck light — clear 24 LED",
    application: "10–30V 24-LED truck light, clear, with rubber grommet",
    category: "Truck & trailer",
    voltage: "10–30V",
    colour: "Clear",
    notes: "Also listed HY-088HC",
  },
  {
    sku: "HY-088H LED31R",
    altCode: "HY-088HR / TL22LED",
    title: "LED truck light — red 24 LED",
    application: "10–30V 24-LED truck light, red",
    category: "Truck & trailer",
    voltage: "10–30V",
    colour: "Red",
  },
  {
    sku: "HY-088H LED31Y",
    altCode: "HY-088HY / TL33LED",
    title: "LED truck light — amber 24 LED",
    application: "10–30V 24-LED truck light, amber, with rubber grommet",
    category: "Truck & trailer",
    voltage: "10–30V",
    colour: "Amber",
    notes: "Alt refs 0101-00016 / 0102-00016",
  },
  {
    sku: "HY-088X-5LED A",
    altCode: "HY-088-5",
    title: "Round marker lamp — amber 12/24V",
    application: "Round amber marker lamp, 12V/24V",
    category: "Marker lamps",
    voltage: "12–24V",
    colour: "Amber",
  },
  {
    sku: "HY140Y",
    stockNo: "HY140Y",
    title: "Matador work light (H3)",
    application: "Matador work light for H3 globe, with plastic holder",
    category: "Work & spot",
    notes: "Uses H3 globe",
  },
  {
    sku: "TL217VM",
    altCode: "TL-217VM",
    title: "LED interior lamp 210×40 mm",
    application: "LED interior lamp, 210×40 mm",
    category: "Interior",
    notes: "Catalogue spelling: INTEROR TL217VM",
  },
  {
    sku: "L36L",
    stockNo: "213335",
    title: "Mercedes truck tail lamp — LH",
    application: "Left-hand tail lamp for Mercedes truck",
    category: "Tail & indicator",
  },
  {
    sku: "LED A2-144/C",
    stockNo: "435221",
    title: "LED light bar — combo flood/spot",
    application: "Combo flood/spot LED light bar",
    category: "Light bars",
  },
  {
    sku: "LED B0105",
    altCode: "B0105",
    title: "LED flood work light 80W 5″",
    application: "10–30V 80W 5″ flood work light",
    category: "Work & spot",
    voltage: "10–30V",
  },
  {
    sku: "LED B0107",
    altCode: "B0107",
    title: "LED spot light 96W 9″ rally",
    application: "10–30V 96W 9″ spot / rally light",
    category: "Work & spot",
    voltage: "10–30V",
  },
  {
    sku: "LED CLC-1018-1L",
    altCode: "CLC-1018-1L / ECT.EL21LED",
    title: "LED Venter trailer lamp — 8 LED",
    application: "10–30V 8-LED Venter trailer lamp",
    category: "Truck & trailer",
    voltage: "10–30V",
  },
  {
    sku: "LED CLC-1018L",
    altCode: "CLC-1018L",
    title: "LED Venter trailer lamp — 8 LED",
    application: "10–30V 8-LED Venter trailer lamp",
    category: "Truck & trailer",
    voltage: "10–30V",
  },
  {
    sku: "LED DB-2002",
    altCode: "DB-2002",
    title: "LED work lamp set 9W 3-LED",
    application: "9W 3-LED work lamp set, 10–30V",
    category: "Work & spot",
    voltage: "10–30V",
    notes: "Sold as a set",
  },
  {
    sku: "LED DB-3015 AMB",
    altCode: "DB3015 AMBER",
    title: "LED side marker — amber",
    application: "12–24V amber side marker",
    category: "Side markers",
    voltage: "12–24V",
    colour: "Amber",
  },
  {
    sku: "LED DB-3015 BLU",
    altCode: "DB-3015 BLUE",
    title: "LED side marker — blue",
    application: "12–24V blue side marker",
    category: "Side markers",
    voltage: "12–24V",
    colour: "Blue",
  },
  {
    sku: "LED DB-3015 RED",
    altCode: "DB3015 RED",
    title: "LED side marker — red",
    application: "12–24V red side marker",
    category: "Side markers",
    voltage: "12–24V",
    colour: "Red",
  },
  {
    sku: "LED DB-3020 AMB",
    altCode: "DB-3020 AMBER",
    title: "LED side marker — amber",
    application: "12–24V amber side marker",
    category: "Side markers",
    voltage: "12–24V",
    colour: "Amber",
  },
  {
    sku: "LED DB-3020 BLU",
    altCode: "DB3020 BLUE / 011000003",
    title: "LED side marker — blue",
    application: "12–24V blue side marker",
    category: "Side markers",
    voltage: "12–24V",
    colour: "Blue",
  },
  {
    sku: "LED DB-3020 GRN",
    altCode: "DB3020 GREEN / TL13VGB-1",
    title: "LED side marker — green",
    application: "12–24V green side marker",
    category: "Side markers",
    voltage: "12–24V",
    colour: "Green",
    notes: "Alt 010700002",
  },
  {
    sku: "LED DB-3020 RED",
    altCode: "DB3020 RED / TL13VRB-1",
    title: "LED side marker — red",
    application: "12–24V red side marker",
    category: "Side markers",
    voltage: "12–24V",
    colour: "Red",
  },
  {
    sku: "LED DB-3020 WTE",
    altCode: "DB3020 WHITE",
    title: "LED side marker — white",
    application: "12–24V white side marker",
    category: "Side markers",
    voltage: "12–24V",
    colour: "White",
    notes: "Alt refs 010700007 / 010800002",
  },
  {
    sku: "LED E0416",
    altCode: "E0416",
    title: "LED light bar 300W combo dim/bright",
    application: "300W combo light bar with dim/bright control",
    category: "Light bars",
  },
  {
    sku: "LED E2507",
    stockNo: "435273",
    title: "LED light bar 288W curved 1125 mm",
    application: "288W curved LED light bar, 1125 mm",
    category: "Light bars",
  },
  {
    sku: "LED F0107",
    altCode: "F0107",
    title: "LED square flood work lamp 24W",
    application: "24W 10–30V square flood work lamp",
    category: "Work & spot",
    voltage: "10–30V",
  },
  {
    sku: "LED F0401",
    altCode: "F0401",
    title: "Forklift oval spot — single 9–80V",
    application: "Oval forklift spot lamp, single, 9–80V",
    category: "Special",
    voltage: "9–80V",
  },
  {
    sku: "LED F0401 RED",
    altCode: "F0401 R",
    title: "Forklift oval spot — single red 9–80V",
    application: "Oval forklift spot lamp, single red, 9–80V",
    category: "Special",
    voltage: "9–80V",
    colour: "Red",
  },
  {
    sku: "LED F0401-2",
    altCode: "F0401-2",
    title: "Forklift oval spot — twin 9–80V",
    application: "Oval forklift spot lamp, twin, 9–80V",
    category: "Special",
    voltage: "9–80V",
  },
  {
    sku: "LED F0402",
    stockNo: "435269",
    title: "Flash strobe amber 12 LED",
    application: "10–30V amber flash strobe, 12 LED",
    category: "Strobe & rotating",
    voltage: "10–30V",
    colour: "Amber",
  },
  {
    sku: "LED F0402 C",
    altCode: "F0402C",
    title: "Flash strobe clear 4 LED",
    application: "10–30V clear flash strobe, 4 LED",
    category: "Strobe & rotating",
    voltage: "10–30V",
    colour: "Clear",
  },
  {
    sku: "LED F0403",
    stockNo: "435270",
    title: "Flash strobe amber 6 LED",
    application: "10–30V amber flash strobe, 6 LED",
    category: "Strobe & rotating",
    voltage: "10–30V",
    colour: "Amber",
  },
  {
    sku: "LED F3-36-36W",
    altCode: "F3-36-36W",
    title: "LED combo light bar 36W 8″",
    application: "10–30V 36W 8″ combo light bar",
    category: "Light bars",
    voltage: "10–30V",
  },
  {
    sku: "LED HY-840-2",
    altCode: "HY840-2",
    title: "LED strobe 36 LED — no adapter",
    application: "12–30V 36-LED strobe without cigarette adapter",
    category: "Strobe & rotating",
    voltage: "12–30V",
  },
  {
    sku: "LED HY-840-32",
    altCode: "HY840-32",
    title: "LED strobe 36 LED — with cig adapter",
    application: "12–30V 36-LED strobe with cigarette adapter",
    category: "Strobe & rotating",
    voltage: "12–30V",
  },
  {
    sku: "LED HY-850",
    altCode: "HY-850",
    title: "LED strobe 54 LED — no adapter",
    application: "12–30V 54-LED strobe without cigarette adapter",
    category: "Strobe & rotating",
    voltage: "12–30V",
  },
  {
    sku: "LED HY-850*",
    altCode: "HY-850-1",
    title: "LED strobe 54 LED — with cig adapter",
    application: "12–30V 54-LED strobe with cigarette adapter",
    category: "Strobe & rotating",
    voltage: "12–30V",
  },
  {
    sku: "LED JR-06 27W R",
    altCode: "JR-06-27W R",
    title: "LED work lamp 27W round thin base",
    application: "12–48V 27W round thin-base work lamp",
    category: "Work & spot",
    voltage: "12–48V",
  },
  {
    sku: "LED JR-06-27W S",
    altCode: "JR-06-27W SQ",
    title: "LED work lamp 27W square thin base",
    application: "12–48V 27W square thin-base work lamp",
    category: "Work & spot",
    voltage: "12–48V",
  },
  {
    sku: "LED R0618",
    altCode: "60618",
    title: "LED square flood work lamp 18W",
    application: "18W square flood work lamp, 10–30V",
    category: "Work & spot",
    voltage: "10–30V",
  },
  {
    sku: "LED RGD1004 RND",
    stockNo: "435200",
    altCode: "ELP.LEDPD27WRND",
    title: "LED work lamp 27W round thick base",
    application: "27W round thick-base work lamp, 12–48V",
    category: "Work & spot",
    voltage: "12–48V",
  },
  {
    sku: "LED RGD1004 SQ",
    stockNo: "435199",
    altCode: "ELP.LEDPD27WSQ",
    title: "LED work lamp 27W square thick base",
    application: "27W square thick-base work lamp, 12–48V",
    category: "Work & spot",
    voltage: "12–48V",
  },
  {
    sku: "LED RGLB016A-4",
    stockNo: "435218",
    title: "LED light bar 72W 24-LED combo 350 mm",
    application: "72W 24-LED combo light bar, 350 mm",
    category: "Light bars",
  },
  {
    sku: "LED RGWL001",
    stockNo: "435192",
    title: "LED round flood work lamp 18W",
    application: "18W round flood work lamp, 10–30V",
    category: "Work & spot",
    voltage: "10–30V",
  },
  {
    sku: "LED RGWL003",
    stockNo: "435193",
    title: "LED square flood work lamp 15W 110 mm",
    application: "15W square flood work lamp, 110 mm",
    category: "Work & spot",
  },
  {
    sku: "LED S0515G-15W",
    altCode: "S0515G-15W",
    title: "LED square flood work lamp 15W 80 mm",
    application: "15W square flood work lamp, 80 mm",
    category: "Work & spot",
  },
  {
    sku: "ML121C12V",
    stockNo: "213338",
    title: "Round LED marker lamp — clear",
    application: "Round LED marker lamp, clear, 12V/24V (lamp only)",
    category: "Marker lamps",
    voltage: "12–24V",
    colour: "Clear",
  },
  {
    sku: "ML121C12VWH",
    stockNo: "213338WH",
    title: "Round marker lamp — clear with holder",
    application: "Round clear marker lamp 12/24V with holder",
    category: "Marker lamps",
    voltage: "12–24V",
    colour: "Clear",
  },
  {
    sku: "ML121G12V",
    stockNo: "213339",
    title: "Round LED marker lamp — green",
    application: "Round LED marker lamp, green, 12/24V (lamp + plastic holder options)",
    category: "Marker lamps",
    voltage: "12–24V",
    colour: "Green",
  },
  {
    sku: "ML121R12V",
    stockNo: "213342",
    title: "Round LED marker lamp — red",
    application: "Round LED marker lamp, red, 12/24V",
    category: "Marker lamps",
    voltage: "12–24V",
    colour: "Red",
  },
  {
    sku: "NL147",
    stockNo: "431328",
    altCode: "LN104",
    title: "Small chrome round number plate lamp",
    application: "Small chrome round number plate lamp (LED lamp only)",
    category: "Number plate",
  },
  {
    sku: "NOP",
    stockNo: "213347",
    altCode: "LN103",
    title: "Chrome oblong number plate lamp",
    application: "Chrome oblong number plate lamp",
    category: "Number plate",
  },
  {
    sku: "RB1000Y",
    stockNo: "219774",
    title: "Round yellow spot lamp",
    application: "Round yellow spot lamp (each)",
    category: "Work & spot",
    colour: "Yellow",
  },
  {
    sku: "ROT TL-61VY-1",
    altCode: "TL-61VY-1",
    title: "Rotating lamp TL61 — 360° bolt-on",
    application: "360° bolt-on rotating lamp TL-61VY-1",
    category: "Strobe & rotating",
  },
  {
    sku: "ROT2RL923111001",
    stockNo: "100126",
    title: "Amber 12V rotating light",
    application: "Amber 12V rotating beacon",
    category: "Strobe & rotating",
    voltage: "12V",
    colour: "Amber",
  },
  {
    sku: "ROTAT 079A",
    stockNo: "215665",
    title: "Large amber 12V rotating lamp",
    application: "Large amber 12V rotating lamp",
    category: "Strobe & rotating",
    voltage: "12V",
    colour: "Amber",
  },
  {
    sku: "ROTAT 98285516A",
    stockNo: "213310",
    title: "Amber rotating lamp 12/24V",
    application: "12/24V amber rotating lamp",
    category: "Strobe & rotating",
    voltage: "12–24V",
    colour: "Amber",
  },
  {
    sku: "ROTAT TL-55VY",
    stockNo: "220799",
    title: "Amber LED rotating — 30 round 360°",
    application: "30-LED round amber rotating beacon, 360°",
    category: "Strobe & rotating",
    colour: "Amber",
  },
  {
    sku: "ROTAT TL-55VY-1",
    stockNo: "220828",
    title: "Amber LED rotating — 30 square bolt-on",
    application: "30-LED square amber rotating beacon, 360°, bolt-on",
    category: "Strobe & rotating",
    colour: "Amber",
  },
  {
    sku: "ROTAT TL-62VY",
    stockNo: "220929",
    title: "Amber LED rotating — 60 square 360°",
    application: "60-LED square amber rotating beacon, 360°",
    category: "Strobe & rotating",
    colour: "Amber",
  },
  {
    sku: "ROTAT WBL001AP",
    stockNo: "220808P",
    altCode: "TL84VY281080V",
    title: "Large amber strobe — pole mount",
    application: "Large amber strobe, pole mount",
    category: "Strobe & rotating",
    colour: "Amber",
  },
  {
    sku: "TL-L197VW",
    stockNo: "434960",
    title: "LED square work lamp 27W",
    application: "27W LED square work lamp, 10–30V",
    category: "Work & spot",
    voltage: "10–30V",
  },
  {
    sku: "TL23LED B",
    altCode: "TL23",
    title: "Bulls-eye stop / tail / indicator",
    application: "12–24V stop-tail-indicator bulls-eye lamp",
    category: "Truck & trailer",
    voltage: "12–24V",
  },
  {
    sku: "TL23LED C",
    stockNo: "425194",
    title: "Bulls-eye reverse lamp — clear",
    application: "12–24V clear reverse bulls-eye lamp",
    category: "Truck & trailer",
    voltage: "12–24V",
    colour: "Clear",
  },
  {
    sku: "TL23LED T",
    altCode: "TL23 T",
    title: "Bulls-eye stop / tail / indicator + grommet",
    application: "12–24V stop-tail-indicator bulls-eye with rubber grommet",
    category: "Truck & trailer",
    voltage: "12–24V",
  },
  {
    sku: "UNV TR A",
    title: "Universal truck light — amber super seal",
    application: "Amber universal super-seal truck light",
    category: "Truck & trailer",
    colour: "Amber",
  },
  {
    sku: "UNV TR C",
    stockNo: "213371",
    title: "Universal truck light — clear",
    application: "Clear universal Truck-Lite style lamp",
    category: "Truck & trailer",
    colour: "Clear",
  },
  {
    sku: "UNV TR R",
    title: "Universal truck light — red super seal",
    application: "Red universal super-seal truck light",
    category: "Truck & trailer",
    colour: "Red",
  },
  {
    sku: "XL403R",
    stockNo: "431346",
    title: "19 LED lamp — red lens 10/30V",
    application: "19-LED lamp with red lens, 10–30V",
    category: "Truck & trailer",
    voltage: "10–30V",
    colour: "Red",
  },
  {
    sku: "XL404Y",
    stockNo: "431345",
    title: "19 LED lamp — amber lens 10/30V",
    application: "19-LED lamp with amber lens, 10–30V",
    category: "Truck & trailer",
    voltage: "10–30V",
    colour: "Amber",
  },
];

export const LAMP_PRODUCT_COUNT = LAMP_PRODUCTS.length;

export const LAMP_CATEGORIES = Array.from(
  new Set(LAMP_PRODUCTS.map((p) => p.category)),
).sort((a, b) => a.localeCompare(b));
